const MAX_DISTRACTOR_NUMBER = 2
const DEFAULT_QUESTIONS_QUANTITY_OCCURRENCES = 1

const EXAM_CONSTANTS = {
    MAX_DISTRACTOR_NUMBER: 2,
    DEFAULT_QUESTIONS_QUANTITY_OCCURRENCES: 1,
    get NUMBER_OF_QUESTIONS() {
        return this.MAX_DISTRACTOR_NUMBER + 1
    },
    PREVIEW_VERSION: 0
}

module.exports = {
    EXAM_CONSTANTS
}